---
jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: workload
    podWait: false
    cleanup: true
    waitWhenFinished: true
    maxWaitTimeout: 5m
    errorOnVerify: true
    defaultMissingKeysWithZero: true
    objects:
    # Templates
      # Template of Gu Pods with fedora-stress-ng
      - objectTemplate: templates/common/configmap.yaml
        replicas: 2
        inputVars:
          group: "guaranteed"
      - objectTemplate: templates/common/secret.yaml
        replicas: 4
        inputVars:
          group: "guaranteed"
      - objectTemplate: templates/guaranteed/deployment.yaml
        replicas: 1
        inputVars:
          Image_stressng: '{{ or .REGISTRY "quay.io/dosman" }}/fedora-stress-ng:aarch64'
          Image_nginx: '{{ or .REGISTRY "quay.io/dosman" }}/sampleapp:aarch64'
          volumes:
            - name: configmap-guaranteed-1
              type: configMap
              path: /var/configmap1
            - name: configmap-guaranteed-2
              type: configMap
              path: /var/configmap2
            - name: secret-guaranteed-1
              type: secret
              path: /var/secret1
            - name: secret-guaranteed-2
              type: secret
              path: /var/secret2
            - name: secret-guaranteed-3
              type: secret
              path: /var/secret3
            - name: secret-guaranteed-4
              type: secret
              path: /var/secret4

      - objectTemplate: templates/guaranteed/service.yaml
        replicas: 1

      - objectTemplate: templates/common/configmap.yaml
        replicas: 2
      - objectTemplate: templates/common/secret.yaml
        replicas: 4

      # Template of burstable pods with exec probes
      - objectTemplate: templates/webserver/webserver-deployment.yaml
        replicas: 4
        inputVars:
          Image_stressng: '{{ or .REGISTRY "quay.io/dosman" }}/fedora-stress-ng:aarch64'
          Image_nginx: '{{ or .REGISTRY "quay.io/dosman" }}/sampleapp:aarch64'
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4
      - objectTemplate: templates/webserver/webserver-service.yaml
        replicas: 4
      - objectTemplate: templates/webserver/curl-deployment.yaml
        replicas: 4
        inputVars:
          Image_nginx: '{{ or .REGISTRY "quay.io/dosman" }}/sampleapp:aarch64'
          Image_curl: '{{ or .REGISTRY "quay.io/dosman" }}/curl'
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4

      # Templates of burstable pods with kubeapiserver reqs
      - objectTemplate: templates/kubectlapp/serviceaccount.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/role.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/rolebinding.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/deployment.yaml
        replicas: 6
        inputVars:
          Image_nginx: '{{ or .REGISTRY "quay.io/dosman" }}/sampleapp:aarch64'
          Image_kubectl: '{{ or .REGISTRY "quay.io/dosman" }}/kubectl:aarch64'
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4
